"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createSocket = exports.deleteSocket = exports.removeSocket = exports.writeSocket = exports.readSocket = exports.closeSocket = exports.connectSocket = exports.updateSocket = exports.initSocket = void 0;
var socket_buzz_1 = require("./buz/socket.buzz");
Object.defineProperty(exports, "initSocket", { enumerable: true, get: function () { return socket_buzz_1.initSocket; } });
var socket_buzz_2 = require("./buz/socket.buzz");
Object.defineProperty(exports, "updateSocket", { enumerable: true, get: function () { return socket_buzz_2.updateSocket; } });
var socket_buzz_3 = require("./buz/socket.buzz");
Object.defineProperty(exports, "connectSocket", { enumerable: true, get: function () { return socket_buzz_3.connectSocket; } });
var socket_buzz_4 = require("./buz/socket.buzz");
Object.defineProperty(exports, "closeSocket", { enumerable: true, get: function () { return socket_buzz_4.closeSocket; } });
var socket_buzz_5 = require("./buz/socket.buzz");
Object.defineProperty(exports, "readSocket", { enumerable: true, get: function () { return socket_buzz_5.readSocket; } });
var socket_buzz_6 = require("./buz/socket.buzz");
Object.defineProperty(exports, "writeSocket", { enumerable: true, get: function () { return socket_buzz_6.writeSocket; } });
var socket_buzz_7 = require("./buz/socket.buzz");
Object.defineProperty(exports, "removeSocket", { enumerable: true, get: function () { return socket_buzz_7.removeSocket; } });
var socket_buzz_8 = require("./buz/socket.buzz");
Object.defineProperty(exports, "deleteSocket", { enumerable: true, get: function () { return socket_buzz_8.deleteSocket; } });
var socket_buzz_9 = require("./buz/socket.buzz");
Object.defineProperty(exports, "createSocket", { enumerable: true, get: function () { return socket_buzz_9.createSocket; } });
//# sourceMappingURL=socket.buzzer.js.map